name: Django CI

on:
  push:
    ranches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - name: Check out sources 
      uses: actions/checkout@v3
    - name: Prepare container
    - run: ./scripts/prepare-container-focal.sh 
    - name: Clone libs
      run: ./clone_libs.sh
    - name: Install bml
      run: ./build_bml.sh
    - name: Install progress
      run: ./build_progress.sh
